version: "3"

services: 
  db:
    image: postgres:15
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   entrypoint: "./run.sh"

volumes:
  db-data: {}
    