version: "3"

services: 
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - development_nginx:/etc/development_nginx/temp
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: postgres:15
    # ports:
    #   - 5432:5432
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - backend_files:/user_data
    # ports:
    #   - 8000:8000
    env_file:
      - .env

volumes:
  db-data: {}
  development_nginx: {}
  backend_files: {}
    
