"""Expand PostAnalytics and UserAnalytics table.

Revision ID: 2828b7aa9930
Revises: 617ded12a3be
Create Date: 2024-10-27 19:03:19.860483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2828b7aa9930'
down_revision: Union[str, None] = '617ded12a3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_analytics', sa.Column('retweets_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('post_analytics', sa.Column('quotes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('post_analytics', sa.Column('replies_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_analytics', sa.Column('posts_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_analytics', 'posts_count')
    op.drop_column('post_analytics', 'replies_count')
    op.drop_column('post_analytics', 'quotes_count')
    op.drop_column('post_analytics', 'retweets_count')
    # ### end Alembic commands ###
