"""Updated User table for profile pic.

Revision ID: 4b09886dbf93
Revises: f8a7a72a860d
Create Date: 2024-10-03 13:53:08.745207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b09886dbf93'
down_revision: Union[str, None] = 'f8a7a72a860d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic_filename', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('bio_text', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'location')
    op.drop_column('user', 'bio_text')
    op.drop_column('user', 'profile_pic_filename')
    # ### end Alembic commands ###
