"""Update Post table for retweets and replies.

Revision ID: 8a679dd533a6
Revises: 912413824154
Create Date: 2024-10-13 20:19:22.321209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a679dd533a6'
down_revision: Union[str, None] = '912413824154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('secondary_content_type', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('secondary_content_file_id', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('post_type', sa.String(length=30), server_default='tweet', nullable=False))
    op.add_column('post', sa.Column('parent_post_ref', sa.Uuid(), nullable=True))
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=900),
               nullable=True)
    op.drop_column('post', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=900),
               nullable=False)
    op.drop_column('post', 'parent_post_ref')
    op.drop_column('post', 'post_type')
    op.drop_column('post', 'secondary_content_file_id')
    op.drop_column('post', 'secondary_content_type')
    # ### end Alembic commands ###
