"""Rectify UserFollowedBy column name.

Revision ID: 912413824154
Revises: 32ee1a4753ce
Create Date: 2024-10-12 20:43:51.171689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912413824154'
down_revision: Union[str, None] = '32ee1a4753ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.add_column('user_followed_by', sa.Column('followed_id', sa.Uuid(), nullable=False))
    op.drop_constraint('user_followed_by_following_id_fkey', 'user_followed_by', type_='foreignkey')
    op.create_foreign_key(None, 'user_followed_by', 'user', ['followed_id'], ['id'])
    op.drop_column('user_followed_by', 'following_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_followed_by', sa.Column('following_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_followed_by', type_='foreignkey')
    op.create_foreign_key('user_followed_by_following_id_fkey', 'user_followed_by', 'user', ['following_id'], ['id'])
    op.drop_column('user_followed_by', 'followed_id')
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
